### ISSUE TITLE
Browser not available on Intercellar through docker

### ISSUE THREAD

**Issue by ymuto802** [martaint/InterCellar#2]
Hi,

Thank you for developing and publishing a tool which will be very useful for visualization of cell-cell communications. I have encountered an error when I tried the package through docker:

Error in utils::browseURL(appUrl) : 
  'browser' must be a non-empty character string

> options(browser="firefox")
> InterCellar::run_app( reproducible = TRUE )

Listening on http://127.0.0.1:6716
sh: firefox: command not found

I would be grateful and also it would be more user-friendly if you could show how to visualize with google chrome or safari on the tutorial.

Thanks,
Yoshi

**Comment by martaint** [comment]
Hi and thank you for trying out InterCellar! :)

Uhm could you please try either of these alternatives:

`options(browser = "/usr/bin/open -a '/Applications/Google Chrome.app'")`
`options(browser = "/usr/bin/open -a '/Applications/Safari.app'")`

Hope it would work out! 

Best,
Marta

**Comment by ymuto802** [comment]
Thank you for your quick response !
Unfortunately they did not work...Maybe not the problem of InterCellar itself but probably related to docker or mac though...
Do you have any ideas how to deal with this problem?

Thanks,
Yoshi

##################################################

> options(browser = "/usr/bin/open -a '/Applications/Google Chrome.app'")
> InterCellar::run_app( reproducible = TRUE )

Listening on http://127.0.0.1:7973
sh: /usr/bin/open: No such file or directory

> options(browser = "/usr/bin/open -a '/Applications/Safari.app'")
> InterCellar::run_app( reproducible = TRUE )

Listening on http://127.0.0.1:7973
sh: /usr/bin/open: No such file or directory

**Comment by martaint** [comment]
Hi,

unfortunately I could not find any other solution :( I guess you tried this already, but what happens if you don't run the 
`options(...)`
and simply try with `InterCellar::run_app( reproducible = TRUE )` ? 

Sorry I don't have access to a mac and I cannot reproduce this error on my linux/windows :(

**Comment by ymuto802** [comment]
Thanks Marta, maybe the problem is related to Mac, and we will use it on windows -  Anyway, thank you very much and good luck !
